# Install scripts. (runs after repo cloning) - http://www.diwebsity.com/2016/03/24/appveyor/
install:
  # Get the latest stable version of Node.js
  - ps: Install-Product node
  # install modules
  - npm install -g gulp
  - npm install

# Post-install test scripts.
test_script:
  # Output useful info for debugging.
  - node --version
  - npm --version
  - echo Gulp Version
  - gulp -v


  - echo %CD%
  - cmd: dir /b

  # run gulp tasks
  #- npm run-script gulp-dist
  - gulp dist
  - cmd: dir /b C:\projects\angular-spa-sample

  # run tests
  #- npm test


# Cache folder to speed up builds
#cache:
#  - node_modules -> package.json # preserve "node_modules" directory in the root of build folder but will reset it if package.json is modified
#  - app/node_modules -> app\package.json
#  - cache   # nw-builder cache
#  - '%APPDATA%\npm-cache'   # npm cache

# which git branch to watch
#branches:
#  only:
#    - master

# Do not build on tags (GitHub only)
#skip_tags: true

artifacts:
  - path: dist
    name: dist

# Don't actually build.
build: off